-- drop tables if exist to ensure clean state
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS classrooms CASCADE;

-- Tạo bảng subjects (Môn học)
CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  credits INTEGER DEFAULT 0,
  certificate_id BIGINT,
  status TEXT DEFAULT 'active'
);

-- Insert dữ liệu mẫu cho Môn học
INSERT INTO subjects (code, name, credits, certificate_id, status) VALUES
('IT01', 'Tin học văn phòng cơ bản', 3, 1, 'active'),
('IT02', 'Tin học văn phòng nâng cao', 3, 2, 'active'),
('NET01', 'Mạng máy tính cơ bản', 4, 3, 'active'),
('PRG01', 'Lập trình Python căn bản', 3, 4, 'active');

-- Bật RLS
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép tất cả đọc môn học" ON subjects FOR SELECT USING (true);
CREATE POLICY "Chỉ nhân viên quản lý môn học" ON subjects FOR ALL USING ( is_admin() OR is_staff() );

-- Tạo bảng classrooms (Phòng học)
CREATE TABLE classrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  building TEXT,
  capacity INTEGER DEFAULT 0,
  type TEXT DEFAULT 'lecture',
  status TEXT DEFAULT 'active'
);

-- Insert dữ liệu mẫu cho Phòng học
INSERT INTO classrooms (code, name, building, capacity, type, status) VALUES
('P501', 'Phòng máy 1', 'Khu C', 40, 'computer', 'active'),
('P502', 'Phòng máy 2', 'Khu C', 40, 'computer', 'active'),
('P503', 'Phòng học lý thuyết 1', 'Khu C', 60, 'lecture', 'active'),
('P504', 'Phòng thi tiêu chuẩn', 'Khu C', 30, 'exam', 'active');

-- Bật RLS
ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép tất cả đọc phòng học" ON classrooms FOR SELECT USING (true);
CREATE POLICY "Chỉ nhân viên quản lý phòng học" ON classrooms FOR ALL USING ( is_admin() OR is_staff() );
