-- 1. Course Classes (Lớp học phần)
CREATE TABLE IF NOT EXISTS course_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  subject_id BIGINT REFERENCES subjects(id),
  instructor_id BIGINT REFERENCES instructors(id),
  start_date DATE,
  end_date DATE,
  max_students INTEGER DEFAULT 40,
  current_students INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active'
);
ALTER TABLE course_classes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read course_classes" ON course_classes;
CREATE POLICY "Public read course_classes" ON course_classes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage course_classes" ON course_classes;
CREATE POLICY "Staff manage course_classes" ON course_classes FOR ALL USING (is_staff());

-- 2. Activity Classes (Lớp sinh hoạt)
CREATE TABLE IF NOT EXISTS activity_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  advisor TEXT,
  max_students INTEGER DEFAULT 40,
  current_students INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active'
);
ALTER TABLE activity_classes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read activity_classes" ON activity_classes;
CREATE POLICY "Public read activity_classes" ON activity_classes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage activity_classes" ON activity_classes;
CREATE POLICY "Staff manage activity_classes" ON activity_classes FOR ALL USING (is_staff());

-- 3. Contracts (Hợp đồng thanh toán)
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  partner TEXT NOT NULL,
  type TEXT,
  value INTEGER DEFAULT 0,
  signed_date DATE,
  status TEXT DEFAULT 'active'
);
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read contracts" ON contracts;
CREATE POLICY "Public read contracts" ON contracts FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage contracts" ON contracts;
CREATE POLICY "Staff manage contracts" ON contracts FOR ALL USING (is_staff());

-- 4. Exam Rooms (Phòng thi & Xếp phòng)
CREATE TABLE IF NOT EXISTS exam_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES exam_sessions(id),
  room_id BIGINT REFERENCES classrooms(id),
  shift TEXT,
  exam_date DATE,
  supervisor TEXT,
  status TEXT DEFAULT 'active'
);
ALTER TABLE exam_rooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read exam_rooms" ON exam_rooms;
CREATE POLICY "Public read exam_rooms" ON exam_rooms FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage exam_rooms" ON exam_rooms;
CREATE POLICY "Staff manage exam_rooms" ON exam_rooms FOR ALL USING (is_staff());

-- 5. Student Scores (Điểm thi)
CREATE TABLE IF NOT EXISTS student_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id BIGINT REFERENCES registrations(id),
  session_id BIGINT REFERENCES exam_sessions(id),
  theory_score NUMERIC(4,2),
  practical_score NUMERIC(4,2),
  total_score NUMERIC(4,2),
  result TEXT,
  status TEXT DEFAULT 'active'
);
ALTER TABLE student_scores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read student_scores" ON student_scores;
CREATE POLICY "Public read student_scores" ON student_scores FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage student_scores" ON student_scores;
CREATE POLICY "Staff manage student_scores" ON student_scores FOR ALL USING (is_staff());
