-- 1. Helper function for staff role
CREATE OR REPLACE FUNCTION is_staff()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_profiles
    WHERE id = auth.uid() AND role IN ('staff', 'admin')
  );
$$;

ALTER FUNCTION is_staff() OWNER TO postgres;

-- 2. Certificates (Chứng chỉ)
CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  fee INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active'
);
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read certs" ON certificates;
CREATE POLICY "Public read certs" ON certificates FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage certs" ON certificates;
CREATE POLICY "Staff manage certs" ON certificates FOR ALL USING (is_staff());

-- 3. Units (Đơn vị liên kết)
CREATE TABLE IF NOT EXISTS units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'active'
);
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read units" ON units;
CREATE POLICY "Public read units" ON units FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage units" ON units;
CREATE POLICY "Staff manage units" ON units FOR ALL USING (is_staff());

-- 4. Banners
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  image TEXT,
  link TEXT,
  "order" INTEGER DEFAULT 1,
  status TEXT DEFAULT 'active'
);
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read banners" ON banners;
CREATE POLICY "Public read banners" ON banners FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage banners" ON banners;
CREATE POLICY "Staff manage banners" ON banners FOR ALL USING (is_staff());

-- 5. Notifications (Thông báo)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  type TEXT,
  date DATE,
  status TEXT DEFAULT 'active'
);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read notifications" ON notifications;
CREATE POLICY "Public read notifications" ON notifications FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage notifications" ON notifications;
CREATE POLICY "Staff manage notifications" ON notifications FOR ALL USING (is_staff());

-- 6. Exam Sessions (Đợt thi)
CREATE TABLE IF NOT EXISTS exam_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  exam_date DATE,
  deadline DATE,
  location TEXT,
  status TEXT DEFAULT 'active'
);
ALTER TABLE exam_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read exam_sessions" ON exam_sessions;
CREATE POLICY "Public read exam_sessions" ON exam_sessions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage exam_sessions" ON exam_sessions;
CREATE POLICY "Staff manage exam_sessions" ON exam_sessions FOR ALL USING (is_staff());

-- 7. Certificate Classes (Lớp chứng chỉ)
CREATE TABLE IF NOT EXISTS certificate_classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  certificate_id BIGINT REFERENCES certificates(id),
  start_date DATE,
  end_date DATE,
  max_students INTEGER DEFAULT 40,
  current_students INTEGER DEFAULT 0,
  fee INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active'
);
ALTER TABLE certificate_classes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read classes" ON certificate_classes;
CREATE POLICY "Public read classes" ON certificate_classes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage classes" ON certificate_classes;
CREATE POLICY "Staff manage classes" ON certificate_classes FOR ALL USING (is_staff());

-- 8. Instructors (Giảng viên)
CREATE TABLE IF NOT EXISTS instructors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  specialization TEXT,
  status TEXT DEFAULT 'active'
);
ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff manage instructors" ON instructors;
CREATE POLICY "Staff manage instructors" ON instructors FOR ALL USING (is_staff());

-- 9. Schedules (Thời khóa biểu)
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT,
  class_name TEXT,
  subject_id BIGINT,
  subject_name TEXT,
  room_id BIGINT,
  room_name TEXT,
  instructor TEXT,
  day_of_week INTEGER,
  start_time TEXT,
  end_time TEXT,
  start_date DATE,
  end_date DATE
);
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read schedules" ON schedules;
CREATE POLICY "Public read schedules" ON schedules FOR SELECT USING (true);
DROP POLICY IF EXISTS "Staff manage schedules" ON schedules;
CREATE POLICY "Staff manage schedules" ON schedules FOR ALL USING (is_staff());

-- 10. Subjects (Môn học)
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  credits INTEGER DEFAULT 0,
  certificate_id BIGINT,
  status TEXT DEFAULT 'active'
);
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Cho phép tất cả đọc môn học" ON subjects;
CREATE POLICY "Cho phép tất cả đọc môn học" ON subjects FOR SELECT USING (true);
DROP POLICY IF EXISTS "Chỉ nhân viên quản lý môn học" ON subjects;
CREATE POLICY "Chỉ nhân viên quản lý môn học" ON subjects FOR ALL USING (is_staff());

-- 11. Classrooms (Phòng học)
CREATE TABLE IF NOT EXISTS classrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  building TEXT,
  capacity INTEGER DEFAULT 0,
  type TEXT DEFAULT 'lecture',
  status TEXT DEFAULT 'active'
);
ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Cho phép tất cả đọc phòng học" ON classrooms;
CREATE POLICY "Cho phép tất cả đọc phòng học" ON classrooms FOR SELECT USING (true);
DROP POLICY IF EXISTS "Chỉ nhân viên quản lý phòng học" ON classrooms;
CREATE POLICY "Chỉ nhân viên quản lý phòng học" ON classrooms FOR ALL USING (is_staff());

-- Insert Base Mock Data to Avoid Empty screens
INSERT INTO certificates (code, name, fee) VALUES ('CNTT_CB', 'Chứng chỉ ứng dụng CNTT cơ bản', 350000) ON CONFLICT DO NOTHING;
INSERT INTO units (code, name) VALUES ('DV01', 'Đại học Bách Khoa') ON CONFLICT DO NOTHING;

INSERT INTO subjects (code, name, credits, certificate_id, status) VALUES
('IT01', 'Tin học văn phòng cơ bản', 3, 1, 'active'),
('IT02', 'Tin học văn phòng nâng cao', 3, 2, 'active'),
('NET01', 'Mạng máy tính cơ bản', 4, 3, 'active'),
('PRG01', 'Lập trình Python căn bản', 3, 4, 'active')
ON CONFLICT DO NOTHING;

INSERT INTO classrooms (code, name, building, capacity, type, status) VALUES
('P501', 'Phòng máy 1', 'Khu C', 40, 'computer', 'active'),
('P502', 'Phòng máy 2', 'Khu C', 40, 'computer', 'active'),
('P503', 'Phòng học lý thuyết 1', 'Khu C', 60, 'lecture', 'active'),
('P504', 'Phòng thi tiêu chuẩn', 'Khu C', 30, 'exam', 'active')
ON CONFLICT DO NOTHING;
